"""empty message

Revision ID: 2ab86fbb564b
Revises: 3f049a4d4de8
Create Date: 2014-12-23 22:55:08.182385

"""

# revision identifiers, used by Alembic.
revision = '2ab86fbb564b'
down_revision = '3f049a4d4de8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
