"""empty message

Revision ID: 2be6d2447447
Revises: 3a154c93a953
Create Date: 2014-12-23 23:58:04.623445

"""

# revision identifiers, used by Alembic.
revision = '2be6d2447447'
down_revision = '3a154c93a953'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_asset_path', sa.String(length=2000), nullable=False),
    sa.Column('entity_status', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_asset_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_asset_id', sa.Integer(), nullable=False),
    sa.Column('entity_asset_attribute_key', sa.String(length=256), nullable=False),
    sa.Column('entity_asset_attribute_value', sa.String(length=256), nullable=False),
    sa.Column('entity_asset_attribute_type', sa.String(length=256), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_asset_attribute')
    op.drop_table('entity_asset')
    ### end Alembic commands ###
