"""empty message

Revision ID: 3294768ed34c
Revises: 2be6d2447447
Create Date: 2014-12-23 23:59:15.594108

"""

# revision identifiers, used by Alembic.
revision = '3294768ed34c'
down_revision = '2be6d2447447'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_asset', sa.Column('entity_asset_format', sa.String(length=50), nullable=False))
    op.add_column('entity_asset', sa.Column('entity_asset_type', sa.String(length=256), nullable=False))
    op.drop_column('entity_asset', 'entity_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_asset', sa.Column('entity_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('entity_asset', 'entity_asset_type')
    op.drop_column('entity_asset', 'entity_asset_format')
    ### end Alembic commands ###
