"""empty message

Revision ID: 36ae0119874c
Revises: 4a3d29bc6c02
Create Date: 2014-12-23 22:10:36.296931

"""

# revision identifiers, used by Alembic.
revision = '36ae0119874c'
down_revision = '4a3d29bc6c02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
