"""empty message

Revision ID: 3a154c93a953
Revises: 2ab86fbb564b
Create Date: 2014-12-23 23:00:53.993857

"""

# revision identifiers, used by Alembic.
revision = '3a154c93a953'
down_revision = '2ab86fbb564b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
