"""empty message

Revision ID: 4a3d29bc6c02
Revises: 12895c48276d
Create Date: 2014-12-23 21:43:29.057619

"""

# revision identifiers, used by Alembic.
revision = '4a3d29bc6c02'
down_revision = '12895c48276d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
